apiVersion: v1
kind: Service
metadata:
  name: fluxcd-policyctl
  namespace: flux-system
  labels:
    app: fluxcd-policyctl
spec:
  type: ClusterIP
  ports:
    - port: 9999
      targetPort: 9999
      protocol: TCP
  selector:
    app: fluxcd-policyctl
